POST http://localhost:5005/model/parse
Content-Type: application/json

{
  "text": "我想办事"
}
###
POST http://localhost:5005/model/parse
Content-Type: application/json; charset=utf-8
Accept: application/json; charset=utf-8

{
  "sender": "1234", 
  "text": "农安县"
}


###
curl -X POST \
  http://localhost:5005/model/parse \
  -H "Content-Type: application/json; charset=utf-8" \
  -H "Accept: application/json; charset=utf-8" \
  -d '{"text": "hi"}'
###
POST http://localhost:5005/webhooks/rest/webhook
Content-Type: application/json; charset=utf-8
Accept: application/json; charset=utf-8

{
  "sender": "user_id",
  "message": "变更工伤登记"
}


###
POST http://116.141.0.116:5005/webhooks/rest/webhook
Content-Type: application/json; charset=utf-8
Accept: application/json; charset=utf-8

{
  "sender": "user_id",
  "message": "/ask_disability_service{\"main_item\": \"就业信息服务\",\"business_item\": \"就业政策法规咨询\",}"
}

###
curl -X POST \
  http://116.141.0.116:5005/webhooks/rest/webhook \
  -H "Content-Type: application/json; charset=utf-8" \
  -H "Accept: application/json; charset=utf-8" \
  -d '{"sender": "test_user","text": "残疾人证办理"}'

curl -X POST http://localhost:5005/webhooks/rest/webhook \
  -H "Content-Type: application/json" \
  -H "Accept: application/json; charset=utf-8" \
  -d '{"sender": "test_user", "message": "hi"}'

### 
POST http://116.141.0.116:5005/webhooks/rest/webhook
Content-Type: application/json; charset=utf-8
Accept: application/json; charset=utf-8

{
  "sender": "user_id",
  "message": "残疾人证办理"
}


### 例子，用于启动详细的流程
POST http://localhost:5005/webhooks/rest/webhook
Content-Type: application/json; charset=utf-8
Accept: application/json; charset=utf-8

{
  "sender": "12345",
  "message": "/ask_service_details{\"main_item\":\"辅助器具异地配置申请\"}"
}


###
POST http://localhost:5678/webhook/7f394fbb-f6b4-4179-b372-337e0a0feb6a/chat
Content-Type: application/json; charset=utf-8
Accept: application/json; charset=utf-8

{
  "sender": "user_id",
  "message": "/ask_disability_service{\"main_item\": \"就业信息服务\",\"business_item\": \"就业政策法规咨询\",}"
}
